(ns katzen.finset.colimits
  "Colimits in the skeletal category of finite sets: initial, coproducts,
   coequalizers, pushouts.

   Mirror of `katzen.finset.limits` — each `initial` / `coproduct` /
   `coequalizer` / `pushout` returns a colimit map of shape
   `{:type … :apex <FinSet> :legs [<FinFunction>…]}` plus whatever
   metadata is needed for the universal property.

   `universal` is a multimethod dispatched on `:type` that builds the
   unique morphism FROM the apex into any compatible cocone.

   The coequalizer uses union-find on the equated pairs; the pushout
   is built as a composite of coproduct + coequalizer (Catlab's
   composite_colimit pattern)."
  (:require [katzen.finset :as fs]))

(defmulti universal
  "Universal arrow out of a colimit into a compatible cocone.

   Second argument shape depends on :type:

   - :initial      — pass the codom FinSet (or its size); returns the
                     unique empty function out of the 0-element apex.
   - :coproduct    — pass a vector of FinFunctions [f g …] each from
                     a summand into a common codom Y; returns apex → Y.
   - :coequalizer  — pass one FinFunction h whose dom is the common
                     codomain of the parallel pair, and that coequalises
                     them; returns apex → h's codom.
   - :pushout      — pass [h k] from the apexes of the span to a common Y
                     such that the square commutes; returns apex → Y."
  (fn [colim _] (:type colim)))

;; ============================================================================
;; Initial: the empty FinSet
;; ============================================================================

(defn initial
  "Initial object: the empty FinSet. Every set has exactly one map FROM it
   (the empty function)."
  []
  {:type :initial
   :apex (fs/fin-set 0)
   :legs []})

(defmethod universal :initial [_colim codom]
  (let [n (cond
            (fs/fin-set? codom)   (fs/cardinality codom)
            (integer? codom)      codom
            :else (throw (ex-info "Bad universal-initial arg" {:got codom})))]
    (fs/fin-function [] n)))

;; ============================================================================
;; Coproduct (binary)
;; ============================================================================

(defn coproduct
  "Binary coproduct A + B in FinSet: apex = |A| + |B|, with the two
   inclusions placing A at [0, |A|) and B at [|A|, |A|+|B|)."
  [a b]
  (let [na (fs/cardinality a)
        nb (fs/cardinality b)
        n  (+ na nb)
        incl1 (fs/fin-function (vec (range na))         n)
        incl2 (fs/fin-function (vec (range na (+ na nb))) n)]
    {:type :coproduct
     :apex (fs/fin-set n)
     :legs [incl1 incl2]
     :summand-sizes [na nb]}))

(defmethod universal :coproduct [colim arrows]
  (let [[f g] arrows]
    (when-not (= (fs/cod f) (fs/cod g))
      (throw (ex-info "coproduct universal: arrows must share a codomain"
                      {:cod-f (fs/cod f) :cod-g (fs/cod g)})))
    (fs/fin-function (into (:vals f) (:vals g)) (fs/cod f))))

(defn coproduct-n
  "n-ary coproduct: fold of binary coproducts."
  [summands]
  (cond
    (empty? summands)        (initial)
    (= 1 (count summands))   (let [a (first summands)]
                               {:type :coproduct
                                :apex a
                                :legs [(fs/id-function a)]
                                :summand-sizes [(fs/cardinality a)]})
    :else
    (let [sizes   (mapv fs/cardinality summands)
          offsets (vec (reductions + 0 (butlast sizes)))
          n       (reduce + 0 sizes)
          incl-i  (fn [i]
                    (let [off (nth offsets i)
                          m   (nth sizes i)]
                      (fs/fin-function (vec (range off (+ off m))) n)))]
      {:type :coproduct
       :apex (fs/fin-set n)
       :legs (mapv incl-i (range (count summands)))
       :summand-sizes sizes
       :offsets offsets})))

;; ============================================================================
;; Coequalizer of a pair f, g : A → B
;; ============================================================================
;;
;; Implementation: union-find over B with each pair (f(i), g(i)) merged.
;; Then renumber the resulting equivalence classes densely 0..k-1.

(defn- find-root [parent x]
  (loop [x x]
    (let [p (nth parent x)]
      (if (= p x) x (recur p)))))

(defn- union [parent x y]
  (let [rx (find-root parent x)
        ry (find-root parent y)]
    (if (= rx ry) parent (assoc parent rx ry))))

(defn coequalizer
  "Coequalizer of f, g : A → B. Apex = B / ~ where the equivalence is
   generated by f(i) ~ g(i) for every i ∈ A. Leg is the canonical
   projection B → B/~."
  [f g]
  (when-not (= (fs/dom f) (fs/dom g))
    (throw (ex-info "coequalizer: parallel arrows must share a domain"
                    {:dom-f (fs/dom f) :dom-g (fs/dom g)})))
  (when-not (= (fs/cod f) (fs/cod g))
    (throw (ex-info "coequalizer: parallel arrows must share a codomain"
                    {:cod-f (fs/cod f) :cod-g (fs/cod g)})))
  (let [na (fs/cardinality (fs/dom f))
        nb (fs/cardinality (fs/cod f))
        final-parent
        (reduce (fn [p i] (union p (fs/app f i) (fs/app g i)))
                (vec (range nb))
                (range na))
        ;; Canonical root per element of B.
        roots-by-elem (mapv #(find-root final-parent %) (range nb))
        ;; Dense renumbering, ordered by smallest representative — keeps
        ;; the projection sorted by class so subsequent operations are
        ;; deterministic.
        ordered-roots (sort (distinct roots-by-elem))
        class-of      (zipmap ordered-roots (range))
        proj-vals     (mapv class-of roots-by-elem)]
    {:type :coequalizer
     :apex (fs/fin-set (count ordered-roots))
     :legs [(fs/fin-function proj-vals (count ordered-roots))]
     :parallel [f g]
     :class-of class-of
     :roots-by-elem roots-by-elem}))

(defmethod universal :coequalizer [colim h]
  ;; h: B → Y must coequalize f and g, so h(f(i)) = h(g(i)) for all i.
  ;; The induced map sends class [b] to h(b) — well-defined when h coequalizes.
  (let [class-of      (:class-of colim)
        roots-by-elem (:roots-by-elem colim)
        [f g]         (:parallel colim)
        ;; Sanity check on a couple of pairs.
        _ (let [na (fs/cardinality (fs/dom f))]
            (doseq [i (range na)]
              (when-not (= (fs/app h (fs/app f i)) (fs/app h (fs/app g i)))
                (throw (ex-info "Universal property failed: h does not coequalize"
                                {:i i
                                 :h-of-f-i (fs/app h (fs/app f i))
                                 :h-of-g-i (fs/app h (fs/app g i))})))))
        ;; For each class k, pick a representative b with root b = the
        ;; k-th smallest root; its h-image is the class's image.
        n-classes (fs/cardinality (:apex colim))
        out (vec (for [k (range n-classes)]
                   (let [root (some (fn [[r idx]] (when (= idx k) r)) class-of)
                         ;; Find any b with roots-by-elem[b] = root.
                         b    (first (keep-indexed (fn [b r] (when (= r root) b))
                                                    roots-by-elem))]
                     (fs/app h b))))]
    (fs/fin-function out (fs/cod h))))

;; ============================================================================
;; Pushout of a span f: C → A, g: C → B
;; ============================================================================
;;
;; Pushout = coequalizer of (incl_A ∘ f, incl_B ∘ g) on A + B. Returns
;; the apex (a quotient of A + B), plus the two legs incl_A ;; coeq-proj
;; and incl_B ;; coeq-proj from A and B respectively into the apex.

(defn pushout
  "Pushout of a span f: C → A, g: C → B. Implemented as a composite
   colimit: coproduct A+B followed by coequalization of (i_A ∘ f, i_B ∘ g)."
  [f g]
  (when-not (= (fs/dom f) (fs/dom g))
    (throw (ex-info "pushout: span arrows must share a domain"
                    {:dom-f (fs/dom f) :dom-g (fs/dom g)})))
  (let [coprod (coproduct (fs/cod f) (fs/cod g))
        [incl-a incl-b] (:legs coprod)
        ;; The two arrows we need to coequalize, both C → A+B.
        af (fs/compose f incl-a)
        bg (fs/compose g incl-b)
        coeq (coequalizer af bg)
        proj (first (:legs coeq))]
    {:type :pushout
     :apex (:apex coeq)
     :legs [(fs/compose incl-a proj) (fs/compose incl-b proj)]
     :span [f g]
     :coproduct coprod
     :coequalizer coeq}))

(defmethod universal :pushout [colim arrows]
  ;; arrows: [h k] from A and B to some Y, square commuting against the span.
  (let [[h k]   arrows
        coprod  (:coproduct colim)
        coeq    (:coequalizer colim)
        ;; Step 1: copair h and k through the coproduct.
        copaired (universal coprod [h k])
        ;; Step 2: factorize through the coequalizer.
        ]
    (universal coeq copaired)))
