(ns katzen.petri
  "Petri nets as ACSets on SchPetri, plus mass-action ODE derivation and a
   compositional builder via UWD junctions (Catlab/AlgebraicPetri style).

   A Petri net here is the standard whole-place / whole-transition variant:
   places (species), transitions, and weighted arcs from species into
   transitions (inputs) and from transitions into species (outputs).
   Arc multiplicities are captured by allowing multiple distinct arcs
   between the same species/transition pair — equivalently, the input and
   output relations are *multisets* of (species, transition) pairs.

   The mass-action ODE is the standard one: for each transition t with
   rate constant k_t,

       rate(t) = k_t · ∏_{s} (X_s)^{in-mult(s, t)}
       dX_s/dt = Σ_t rate(t) · (out-mult(s, t) − in-mult(s, t))

   Composition via UWDs: each box's value is a Petri net plus an integer
   vector saying which species each port refers to. `compose-petri`
   takes the disjoint union of all box nets, then quotients the species
   set by the equivalence generated by 'ports attached to the same
   junction → those species are equal'. This is the FinSet pushout that
   underlies AlgebraicPetri's `oapply` for the relations operad.

   A `PetriDynamics` record bundles a Petri net with its rate constants
   and implements `katzen.compile.core/RasterCompilable` — the protocol
   that lets one driver compile any categorical object into a raster
   ODE RHS. Use `(petri-dynamics net rates)` to get one, then call
   `katzen.compile.core/compile-rhs` (for the typed ftm path) or
   `compile-clojure-rhs` (vanilla Clojure)."
  (:require [katzen.acset :as a]
            [katzen.compile.core :as cc]
            [katzen.finset :as fs]
            [katzen.finset.colimits :as colim]
            [katzen.uwd :as uwd]))

;; ============================================================================
;; SchPetri
;; ============================================================================

(def SchPetri
  "Whole-place / whole-transition Petri net schema."
  {:name       'SchPetri
   :objects    [:S :T :I :O]
   :homs       [{:name :is :dom :I :codom :S}
                {:name :it :dom :I :codom :T}
                {:name :os :dom :O :codom :S}
                {:name :ot :dom :O :codom :T}]
   :attr-types []
   :attrs      []})

;; ============================================================================
;; Constructors
;; ============================================================================

(defn petri
  "Empty Petri net."
  []
  (a/vector-acset SchPetri))

(defn add-species
  "Allocate a species (place). Returns [new-net s-id]."
  [n]
  (a/add-part n :S))

(defn add-species*
  "Allocate k species. Returns [new-net s-ids]."
  [n k]
  (a/add-parts n :S k))

(defn add-transition
  "Allocate a transition. Returns [new-net t-id]."
  [n]
  (a/add-part n :T))

(defn add-input
  "Add a single input arc from species `s` into transition `t`. Multi-arcs
   are modelled by repeated calls. Returns [new-net i-id]."
  [n s t]
  (let [[n i] (a/add-part n :I)]
    [(-> n (a/set-subpart :is i s) (a/set-subpart :it i t)) i]))

(defn add-input-mult
  "Add `k` input arcs from species `s` into transition `t`."
  [n s t k]
  (reduce (fn [[n _] _] (add-input n s t)) [n nil] (range k))
  (first (reduce (fn [[n _] _] (add-input n s t)) [n nil] (range k))))

(defn add-output
  "Add a single output arc from transition `t` into species `s`. Returns
   [new-net o-id]."
  [n s t]
  (let [[n o] (a/add-part n :O)]
    [(-> n (a/set-subpart :os o s) (a/set-subpart :ot o t)) o]))

;; ============================================================================
;; Multiplicity tables
;; ============================================================================

(defn species [n] (vec (a/parts n :S)))
(defn transitions [n] (vec (a/parts n :T)))

(defn in-multiplicity
  "Returns {t → {s → k}}: the number of input arcs from species s into
   transition t."
  [n]
  (reduce (fn [acc i]
            (let [s (a/subpart n :is i)
                  t (a/subpart n :it i)]
              (update-in acc [t s] (fnil inc 0))))
          {}
          (a/parts n :I)))

(defn out-multiplicity
  "Returns {t → {s → k}}: the number of output arcs from transition t
   into species s."
  [n]
  (reduce (fn [acc o]
            (let [s (a/subpart n :os o)
                  t (a/subpart n :ot o)]
              (update-in acc [t s] (fnil inc 0))))
          {}
          (a/parts n :O)))

;; ============================================================================
;; Mass-action ODE
;; ============================================================================

(defn natural-layout
  "The natural state-vector layout for a Petri net: species labels in
   `(species net)` order, mapped to slots 0..n-1."
  [net]
  (cc/state-layout (species net)))

(defn- precompute-pairs
  "Given a Petri net and a state layout, precompute per-transition vectors
   of [global-slot multiplicity] for inputs and outputs. Returns a map
   {:ts <transition ids> :in {t pairs} :out {t pairs}} that both the
   Clojure and raster emitters share."
  [net layout]
  (let [ts       (transitions net)
        slot-of  #(cc/slot layout %)
        in-mult  (in-multiplicity net)
        out-mult (out-multiplicity net)]
    {:ts  ts
     :in  (into {} (for [t ts]
                     [t (mapv (fn [[s k]] [(slot-of s) (long k)])
                              (get in-mult t {}))]))
     :out (into {} (for [t ts]
                     [t (mapv (fn [[s k]] [(slot-of s) (long k)])
                              (get out-mult t {}))]))}))

(defn accumulate-clojure
  "Return a `(fn [du u t])` that ACCUMULATES (without zeroing) the
   mass-action contributions of `net` into `du`, indexing through
   `layout`. Used both as the slow-path body for `RasterCompilable` and
   inside `petri->derivative` (which prepends the zero-out)."
  [net rates layout]
  (let [{:keys [ts in out]} (precompute-pairs net layout)]
    (fn accumulate [^doubles du ^doubles u _t]
      (doseq [t ts]
        (let [k         (double (get rates t 0.0))
              in-pairs  (get in t)
              out-pairs (get out t)
              mass      (reduce
                         (fn [acc [^long s ^long mult]]
                           (* acc (Math/pow (aget u s) mult)))
                         1.0
                         in-pairs)
              rate      (* k mass)]
          (doseq [[^long s ^long mult] in-pairs]
            (aset du s (- (aget du s) (* rate mult))))
          (doseq [[^long s ^long mult] out-pairs]
            (aset du s (+ (aget du s) (* rate mult)))))))))

(defn- factor-expr
  "Source for u[slot]^mult. Direct aget for mult=1, Math/pow otherwise."
  [slot ^long mult]
  (case mult
    1 `(raster.arrays/aget ~'u ~slot)
    `(Math/pow (raster.arrays/aget ~'u ~slot) ~mult)))

(defn- transition-block
  "Per-transition unrolled source block: compute the rate, apply input/
   output contributions to du. Slots in `in-pairs`/`out-pairs` are
   already global (via the layout)."
  [k in-pairs out-pairs]
  (let [rate-sym (gensym "rate")
        rate-expr
        (if (empty? in-pairs)
          (double k)
          (reduce (fn [acc [s m]] `(raster.numeric/* ~acc ~(factor-expr s m)))
                  (double k)
                  in-pairs))]
    `(let [~rate-sym ~rate-expr]
       ~@(for [[s ^long mult] in-pairs]
           `(raster.arrays/aset ~'du ~s
                                (raster.numeric/- (raster.arrays/aget ~'du ~s)
                                                  (raster.numeric/* ~rate-sym ~(double mult)))))
       ~@(for [[s ^long mult] out-pairs]
           `(raster.arrays/aset ~'du ~s
                                (raster.numeric/+ (raster.arrays/aget ~'du ~s)
                                                  (raster.numeric/* ~rate-sym ~(double mult))))))))

(defn accumulate-raster
  "Sequence of source forms that ACCUMULATE (without zeroing) the
   mass-action contributions of `net` into `du`, indexed through
   `layout`. Used as the raster-body for `PetriDynamics` and by
   composite compilers (e.g. UWD-of-dynamics) that concatenate
   per-box bodies."
  [net rates layout]
  (let [{:keys [ts in out]} (precompute-pairs net layout)]
    (for [t ts
          :let [k         (get rates t 0.0)
                in-pairs  (get in t)
                out-pairs (get out t)]]
      (transition-block k in-pairs out-pairs))))

(defn petri->derivative
  "Build an in-place derivative function suitable for raster.ode/ode-problem.

   Returns a fn (fn [du u _t]) that:
     - zeros du,
     - for each transition t with rate constant `(rates t)`:
         rate = (rates t) * prod over species s of X_s^{in-mult(s, t)}
         du[s] += rate * (out-mult(s, t) - in-mult(s, t))   for every s

   State-vector indices correspond to `(species net)` in order: species
   index i in the vector = (nth (species net) i).

   Kept as a thin convenience over `accumulate-clojure` + a zero-out."
  [net rates]
  (let [layout    (natural-layout net)
        accumulate (accumulate-clojure net rates layout)
        n         (:size layout)]
    (fn ode-rhs [^doubles du ^doubles u t]
      (dotimes [i n] (aset du i 0.0))
      (accumulate du u t))))

;; ============================================================================
;; PetriDynamics — a RasterCompilable bundling a Petri net + rate constants
;; ============================================================================

(defrecord PetriDynamics [net rates]
  cc/RasterCompilable
  (-state-layout [_] (natural-layout net))
  (-raster-body  [_ layout] (accumulate-raster  net rates layout))
  (-clojure-body [_ layout] (accumulate-clojure net rates layout)))

(defn petri-dynamics
  "Bundle a Petri net `net` with a rate map `rates` (transition-id →
   rate constant) as a value implementing
   `katzen.compile.core/RasterCompilable`. Hand to `compile-rhs` or
   `compile-clojure-rhs` for an evaluatable ODE right-hand side."
  [net rates]
  (->PetriDynamics net rates))

;; ============================================================================
;; Minimal RK4 integrator
;; ============================================================================
;;
;; Vanilla Clojure RK4 — small, zero-dep, sufficient for the SIR demo and
;; the kind of non-stiff mass-action systems that come out of small Petri
;; nets. For stiff systems or larger state vectors we'd switch to raster's
;; Tsit5/Rosenbrock, but raster's typed-fn (`ftm`/`deftm`) APIs are
;; macro-time only — they don't compose with runtime-built derivative
;; closures yet. Bridge work belongs in a separate polish step.

(defn integrate-rk4
  "Fixed-step RK4 integration. Returns {:ts <vec> :us <vec of double-array>}.

   Arguments:
     f        derivative fn (fn [du u t]) writing into du in-place
     u0       initial state (double-array; coerced from a seq if needed)
     t0, tf   time span
     dt       step size
     save-every  emit every k-th step into :us (default 1)"
  ([f u0 t0 tf dt] (integrate-rk4 f u0 t0 tf dt 1))
  ([f u0 t0 tf dt save-every]
   (let [u0 (double-array u0)
         n  (alength u0)
         u  (aclone u0)
         k1 (double-array n) k2 (double-array n)
         k3 (double-array n) k4 (double-array n)
         tmp (double-array n)
         total-steps (long (Math/ceil (/ (- tf t0) dt)))]
     (loop [step 0
            t (double t0)
            out-ts (transient [(double t0)])
            out-us (transient [(aclone u0)])]
       (if (or (>= step total-steps) (>= t tf))
         {:ts (persistent! out-ts)
          :us (persistent! out-us)}
         (let [;; k1 = f(u, t)
               _ (f k1 u t)
               ;; k2 = f(u + dt/2 * k1, t + dt/2)
               _ (dotimes [i n] (aset tmp i (+ (aget u i) (* (/ dt 2.0) (aget k1 i)))))
               _ (f k2 tmp (+ t (/ dt 2.0)))
               ;; k3 = f(u + dt/2 * k2, t + dt/2)
               _ (dotimes [i n] (aset tmp i (+ (aget u i) (* (/ dt 2.0) (aget k2 i)))))
               _ (f k3 tmp (+ t (/ dt 2.0)))
               ;; k4 = f(u + dt * k3, t + dt)
               _ (dotimes [i n] (aset tmp i (+ (aget u i) (* dt (aget k3 i)))))
               _ (f k4 tmp (+ t dt))
               ;; u_{n+1} = u_n + dt/6 * (k1 + 2k2 + 2k3 + k4)
               _ (dotimes [i n]
                   (aset u i
                         (+ (aget u i)
                            (* (/ dt 6.0)
                               (+ (aget k1 i)
                                  (* 2.0 (aget k2 i))
                                  (* 2.0 (aget k3 i))
                                  (aget k4 i))))))
               next-step (inc step)
               next-t    (+ t dt)
               save?     (or (zero? (mod next-step save-every))
                             (>= next-t tf))
               out-ts'   (if save? (conj! out-ts next-t)        out-ts)
               out-us'   (if save? (conj! out-us (aclone u))    out-us)]
           (recur next-step next-t out-ts' out-us')))))))

;; ============================================================================
;; Composition via UWD
;; ============================================================================
;;
;; Catlab's AlgebraicPetri composes a UWD `d` with a per-box Petri net by:
;;   1. Disjoint-uniting the per-box species (a coproduct in FinSet),
;;   2. Quotienting that union by 'two species are equal if their ports are
;;      attached to the same junction' (a coequalizer in FinSet, computed
;;      by union-find),
;;   3. Re-indexing every box's transitions/inputs/outputs through the
;;      quotient.
;;
;; The per-box specification is: a Petri net N_b and a vector port→species
;; saying which species of N_b each of b's ports refers to.

(defn compose-petri
  "Compose Petri nets through a UWD pattern.

   Arguments:
     d                UWD (katzen.uwd)
     box->net         map {box-id → Petri net for that box}
     box->port-species  map {box-id → vector of species ids, one per port
                          of the box, in port order — saying which species
                          in box->net[b] each of b's ports refers to}

   Returns: a Petri net whose species are the equivalence classes induced
   by 'ports on the same junction → same species'. Transitions and arcs
   are the disjoint union of the boxes' transitions/arcs, re-indexed to
   point to the quotient species."
  [d box->net box->port-species]
  (let [boxes (vec (uwd/boxes d))
        ;; Coproduct of species across all boxes: each box's species set
        ;; lives in a contiguous block of the global "species union".
        sizes (mapv (fn [b] (count (species (get box->net b)))) boxes)
        offsets (vec (reductions + 0 (butlast sizes)))
        offset-of (zipmap boxes offsets)
        total (reduce + 0 sizes)
        ;; Build a global species ID for each (box, local-species-index).
        global-of (fn [b local-idx] (+ (offset-of b) local-idx))
        ;; The equivalence: for each junction j, every (box, port-on-b-at-j)
        ;; pair refers to a species; all such species are equal.
        ;; Encode as two FinFunctions f, g : pair-index → global-species
        ;; where f(k) and g(k) name two species that must be merged.
        pairs-by-junction
        (for [j (uwd/junctions d)
              :let [ps (uwd/junction-ports d j)]
              :when (>= (count ps) 2)
              i (range (dec (count ps)))]
          [(let [p1 (nth ps i)
                 b  (uwd/port-box d p1)
                 idx (.indexOf ^java.util.List (uwd/box-ports d b) p1)
                 local-s (nth (get box->port-species b) idx)
                 local-idx (.indexOf ^java.util.List (species (get box->net b)) local-s)]
             (global-of b local-idx))
           (let [p2 (nth ps (inc i))
                 b  (uwd/port-box d p2)
                 idx (.indexOf ^java.util.List (uwd/box-ports d b) p2)
                 local-s (nth (get box->port-species b) idx)
                 local-idx (.indexOf ^java.util.List (species (get box->net b)) local-s)]
             (global-of b local-idx))])
        f (fs/fin-function (mapv first pairs-by-junction) total)
        g (fs/fin-function (mapv second pairs-by-junction) total)
        ;; Coequalize: produces a projection global-species → quotient-class.
        coeq (colim/coequalizer f g)
        proj (first (:legs coeq))
        n-classes (fs/cardinality (:apex coeq))
        class-of-global (fn [gs] (fs/app proj gs))

        ;; Now assemble the result Petri net.
        ;; Seed: a fresh net with n-classes species pre-allocated.
        [seed _] (add-species* (petri) n-classes)
        ;; For each box, add transitions and re-index arcs.
        result
        (reduce
         (fn [net b]
           (let [src (get box->net b)
                 sps (species src)
                 ts  (transitions src)
                 species-class
                 (fn [local-s]
                   (let [idx (.indexOf ^java.util.List sps local-s)]
                     (inc (class-of-global (global-of b idx)))))
                 ;; We allocate one new transition per source transition.
                 [net t-map]
                 (reduce
                  (fn [[net tm] t]
                    (let [[net new-t] (add-transition net)]
                      [net (assoc tm t new-t)]))
                  [net {}]
                  ts)
                 ;; Re-add inputs.
                 net
                 (reduce
                  (fn [net i]
                    (let [s (a/subpart src :is i)
                          t (a/subpart src :it i)
                          [net _] (add-input net (species-class s) (get t-map t))]
                      net))
                  net
                  (a/parts src :I))
                 ;; Re-add outputs.
                 net
                 (reduce
                  (fn [net o]
                    (let [s (a/subpart src :os o)
                          t (a/subpart src :ot o)
                          [net _] (add-output net (species-class s) (get t-map t))]
                      net))
                  net
                  (a/parts src :O))]
             net))
         seed
         boxes)]
    result))
